---
name: Build and publish packages

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build artifacts
        run: |
          ./tools/test-build ant
          ant release
          ant docs
      - name: Create and Upload Release Assets
        run: |
          set -x
          assets=()
          touch SHASUMS
          touch MD5
          for asset in ./artifacts/*; do
            assets+=("-a" "$asset")
            filename=$(basename -- "$asset")
            sha=$(sha256sum $asset)
            IFS=' ' read -r -a array <<< "$sha"
            echo "${array[0]} $filename" >> SHASUMS
            md5=$(md5sum $asset)
            IFS=' ' read -r -a array <<< "$md5"
            echo "${array[0]} $filename" >> MD5
          done
          assets+=("-a" SHASUMS)
          assets+=("-a" MD5)
          tag_name="${GITHUB_REF##*/}"
          hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

