---
name: Build and publish packages

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build artifacts
        run: ./tools/test-build ant
      - name: Create and Upload Release Assets
        run: |
          set -x
          assets=()
          for asset in ./artifacts/*.jar; do
            assets+=("-a" "$asset")
          done
          tag_name="${GITHUB_REF##*/}"
          hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

